FROM ubuntu:focal

RUN apt-get update && \
    apt-get install -y wget sudo curl

# JDK
RUN apt-get install -y openjdk-11-jdk

# sbt
RUN apt-get install -y apt-transport-https gnupg2
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
  curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add && \
  apt-get update && \
  apt-get install -y sbt

# scala install
RUN wget https://downloads.lightbend.com/scala/2.13.2/scala-2.13.2.deb && \
    dpkg -i scala-2.13.2.deb && \
    rm scala-2.13.2.deb

# node
RUN apt-get install -y nodejs

# other
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y vim-nox

RUN apt-get install -y ctags tig

RUN useradd --uid $USERID --home-dir $HOME --user-group $USER
RUN echo "$USER   ALL = NOPASSWD: ALL" >> /etc/sudoers
USER $USER:$USER

ENTRYPOINT ["bash", "-l"]

