FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y wget sudo

# JDK
RUN apt-get install -y openjdk-8-jdk

# sbt
RUN apt-get install -y apt-transport-https
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
RUN apt-get update && apt-get install -y sbt

# scala install
RUN wget www.scala-lang.org/files/archive/scala-2.12.4.deb && \
    dpkg -i scala-2.12.4.deb && \
    rm scala-2.12.4.deb

# python
RUN apt-get install -y python2.7 python-pip python-setuptools && \
    pip2 install sexpdata websocket-client

RUN apt-get install -y vim-nox-py2

RUN apt-get install -y ctags tig

RUN useradd --uid $USERID --home-dir $HOME --user-group $USER
RUN echo "$USER   ALL = NOPASSWD: ALL" >> /etc/sudoers
USER $USER:$USER

ENTRYPOINT ["bash", "-l"]

